---
# tasks file for homedir-login
- name: .profile base
  copy:
    src: profile.sh
    dest: $HOME/.profile

- name: .profile.d directory
  file:
    path: $HOME/.profile.d
    state: directory
    mode: 0755
